---
title: "Wrangle rows and columns"
format: html
---
# Instructions

This week, you learned about several more pandas methods and attributes. These functions help you work with the columns in your data set.

You'll use these skills to add new columns that calculate the cumulative number of cases and deaths across states.

To learn more about the variables contained in the data set, refer to the data dictionary
[here](https://rstudio.github.io/academy-python-covid/assets/covid_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off

```

## Wrangle rows and columns

In this milestone, you'll create a new variable that calculates the cumulative values of `cases` and `deaths` across states. 

## Recreation

### Part 1 - Import

First, import your data set:

1. Use the code chunk below to read the data from the data file `covid.csv`,
which is stored in the `data/` folder in your working directory
2. Save the data set to a variable named `covid`

```{python}
#| label: 'recreation-import'
```

### Part 2a - Create Columns

Run the code below to see a table.

```{python}
#| label: 'recreate-this'
#| message: false

solution = pd.read_csv('data/milestone02.csv')
solution
```

Your task is to use what you've learned to transform `covid` into this table.

You will need to:

1. Subset `covid` for records where the state is `NY` and save the result as a new data set named `subset`. 
2. Continuing to work with `subset`, create a new column named `cumul_cases`, which contains the result of `.cumsum()`.
3. Still within `subset`, create a new column named `cumul_deaths`, which contains the result of `.cumsum()`.

Work in the code chunk below for your table transformation:

```{python}
#| label: 'recreation-create'

```

Run the following code chunk to test whether your table matches the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
subset.reset_index(drop=True).compare(solution)
```

### Part 2b - Manipulate columns

Your next task is to create two new columns, `cumul_cases_millions` and `cumul_deaths_millions` that contain the values from `cumul_cases` and `cumul_deaths` divided by 1000000. This will make the values easier to interpret when we plot them later.

```{python}
#| label: 'millions'


```

### Part 3 - Visualize

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone02.png` to open an image in the Editor pane

Your task is to recreate this plot using your updated version of `subset`.

Use the chunk below to recreate this plot.

```{python}
#| label: 'recreation-visualize'

```

## Extension

Using the code chunk below, investigate a research question about this data, using the additional data wrangling skills you learned this week. Some ideas:

1. This milestone focused on patterns in `cases` and `deaths` over time, just within New York. What patterns do you see in the _ratio_ of `deaths` to `cases`, over time, within New York and elsewhere? (Compare states of your choosing.)

2. Based on _either_ `cases` or `deaths`, divide this data into groups of your choosing (e.g. low/medium/high, above/below a national average, etc.) and explore patterns based on these groups.

3. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Create at least one new variable in your data set using mathematical operations
3. Use your updated data set to create at least one graph and/or table

```{python}
#| label: 'extension'

```
